Ot89 409 screen detalle de novedad
alkemyTech/OT-89-Client pull request #37
Opened 2021-11-10 23:53 UTC by ilqcho

COMO: Usuario
QUIERO: Conocer el detalle de una novedad
PARA: Tener la info sobre ella

Criterios de aceptación: Al ingresar a la ruta /novedad/:id . Mostrará el detalle de la novedad, obteniendo los datos desde el endpoint de detalle de novedad. En el caso de que el mismo no exista, deberá mostrar un error.

2021-11-11 22:11 UTC, nepha199 requested changes
Comproba el disparo del Alert

2021-11-11 22:11 UTC, nepha199 commented on src/components/Novelty/Novelty.js
> +        getData();
y xq se dispararia el catch?? si no estas validando el response y el apiService no tiene nada que pueda llegar a dispararlo. Tambien podrias plantear el getData como una funcion autoejecutable ya que no la reutilizas en otro lado `(async () => { ...acciones del getData ...})() `

2021-11-12 15:11 UTC, ilqcho commented on src/components/Novelty/Novelty.js
> +        getData();
Alerta arreglada, con la funcion autoejecutable lo probe y no me anduvo por eso lo deje asi

2021-11-12 15:54 UTC, nepha199 approved these changes

2021-11-13 19:49 UTC, Chamarez approved these changes

2021-11-15 13:12 UTC, mframirezfuentes approved these changes

2021-11-15 17:25 UTC, luciano393 approved these changes

2021-11-15 17:25 UTC, merged