handleDelete
alkemyTech/OT-89-Client pull request #46
Opened 2021-11-17 18:11 UTC by luciano393

COMO: Usuario administrador
QUIERO: Eliminar categorias que no necesite mas
PARA: Que esten actualizadas

Criterios de aceptación: Al hacer click en el botón eliminar, mostrar una alerta de confirmación. En el caso de confirmar realizar la petición DELETE al endpoint para eliminar el elemento, y quitarlo de la vista

2021-11-17 22:04 UTC, ilqcho commented on src/components/ActionsHandlers/HandleClicks/handleDelete.jsx
> +        if (deleteResult.data.message === "categoria eliminada") {
Esta echo el action para eliminar ?

2021-11-18 14:43 UTC, mframirezfuentes approved these changes

2021-11-19 12:30 UTC, nepha199 requested changes
Toque delete y se inicio el debugger con este error

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks [...]

![image](https://user-images.githubusercontent.com/80648005/142622987-42c64637-2e35-44dc-ab6f-824c947609f0.png)

2021-11-19 17:32 UTC, coltking approved these changes

2021-11-19 17:34 UTC, bvonpotobsky approved these changes

2021-11-19 17:35 UTC, merged