Set up alert
alkemyTech/OT-89-Client pull request #9
Opened 2021-10-29 18:29 UTC by mframirezfuentes

1. - Dinamic alerta. has been created a component with different parameters. 
2. - Alert to confirm , information and error.  
3. - Aplication to useState, initialize in false.

2021-10-30 13:30 UTC, nepha199 commented on src/components/Alerts/Alert.js
> +const [alert, setAlert] = useState(false)
No se esta usando

2021-10-30 20:37 UTC, mframirezfuentes commented on src/components/Alerts/Alert.js
> +const [alert, setAlert] = useState(false)
Lo dejé como un componente para que después se utilicé en donde se desee llamar. No sé si es la mejor forma
> el alert useState no se esta usando en ningun modo

2021-11-01 13:57 UTC, hfoncea commented on src/components/Alerts/Alert.js
> +const [alert, setAlert] = useState(false)
si no se usa el use state...hay que sacarlo

2021-11-06 22:26 UTC, luciano393 requested changes
Fer necesito que hagas unos cambios.

2021-11-06 23:01 UTC, closed without merging